bestScores = [78.12, 57.42, 57.42]
bestFindings = [
    {
        'generalTM': {
            'columnDimensions': (2, 6048),
            'seed': 42,
            'activationThreshold': 4,
            'cellsPerColumn': 32,
            'connectedPermanence': 0.5,
            'minThreshold': 4,
            'predictedSegmentDecrement': 0.0,
            'permanenceDecrement': 0.05,
            'initialPermanence': 0.4,
            'permanenceIncrement': 0.05,
            'maxNewSynapseCount': 4
        },
        'actionTM': {
            'columnDimensions': (24,),
            'seed': 42,
            'activationThreshold': 4,
            'cellsPerColumn': 32,
            'connectedPermanence': 0.5,
            'minThreshold': 4,
            'predictedSegmentDecrement': 0.0,
            'permanenceIncrement': 0.05,
            'initialPermanence': 0.4,
            'permanenceDecrement': 0.05,
            'maxNewSynapseCount': 4
        },
        'wordTM': {
            'columnDimensions': (189,),
            'seed': 42,
            'activationThreshold': 4,
            'cellsPerColumn': 32,
            'connectedPermanence': 0.5,
            'minThreshold': 4,
            'predictedSegmentDecrement': 0.0,
            'permanenceIncrement': 0.05,
            'initialPermanence': 0.4,
            'permanenceDecrement': 0.05,
            'maxNewSynapseCount': 4
        },
        'actionSP': {
            'columnDimensions': (24,),
            'inputDimensions': (264,),
            'numActiveColumnsPerInhArea': -1.0,
            'seed': 42,
            'spVerbosity': 0,
            'stimulusThreshold': 0,
            'synPermInactiveDec': 0.1,
            'localAreaDensity': 0.02,
            'maxBoost': 3,
            'potentialRadius': 12,
            'dutyCyclePeriod': 10,
            'synPermConnected': 0.1,
            'synPermActiveInc': 0.1,
            'potentialPct': 0.5,
            'wrapAround': True,
            'minPctOverlapDutyCycle': 0.1,
            'minPctActiveDutyCycle': 0.1,
            'globalInhibition': True
        },
        'wordSP': {
            'columnDimensions': (189,),
            'inputDimensions': (869,),
            'numActiveColumnsPerInhArea': -1.0,
            'seed': 42,
            'spVerbosity': 0,
            'stimulusThreshold': 0,
            'potentialRadius': 12,
            'localAreaDensity': 0.02,
            'maxBoost': 3,
            'synPermInactiveDec': 0.1,
            'dutyCyclePeriod': 10,
            'synPermConnected': 0.1,
            'synPermActiveInc': 0.1,
            'potentialPct': 0.5,
            'wrapAround': True,
            'minPctOverlapDutyCycle': 0.1,
            'minPctActiveDutyCycle': 0.1,
            'globalInhibition': True
        }
    }, {
        'generalTM': {
            'activationThreshold': 4,
            'cellsPerColumn': 43,
            'connectedPermanence': 0.5,
            'minThreshold': 4,
            'potentialRadius': 0.0,
            'permanenceDecrement': 0.05,
            'initialPermanence': 0.4,
            'permanenceIncrement': 0.05,
            'maxNewSynapseCount': 4
        },
        'actionTM': {
            'columnDimensions': (24,),
            'activationThreshold': 4,
            'cellsPerColumn': 32,
            'connectedPermanence': 0.5,
            'minThreshold': 4,
            'potentialRadius': 0.0,
            'permanenceIncrement': 0.05,
            'initialPermanence': 0.4,
            'permanenceDecrement': 0.05,
            'maxNewSynapseCount': 4
        },
        'wordTM': {
            'activationThreshold': 4,
            'cellsPerColumn': 32,
            'connectedPermanence': 0.5,
            'minThreshold': 4,
            'potentialRadius': 0.0,
            'permanenceIncrement': 0.05,
            'initialPermanence': 0.4,
            'permanenceDecrement': 0.05,
            'maxNewSynapseCount': 4
        },
        'actionSP': {
            'stimulusThreshold': 0,
            'synPermInactiveDec': 0.1,
            'localAreaDensity': -1.0,
            'maxBoost': 3,
            'potentialRadius': 12,
            'dutyCyclePeriod': 10,
            'synPermConnected': 0.1,
            'synPermActiveInc': 0.15005926560427604,
            'potentialPct': 0.5,
            'wrapAround': True,
            'minPctOverlapDutyCycle': 0.1,
            'globalInhibition': True
        },
        'wordSP': {
            'stimulusThreshold': 0,
            'potentialRadius': 12,
            'localAreaDensity': -1.0,
            'maxBoost': 3,
            'synPermInactiveDec': 0.1,
            'dutyCyclePeriod': 10,
            'synPermConnected': 0.1,
            'synPermActiveInc': 0.1,
            'potentialPct': 0.5,
            'wrapAround': True,
            'minPctOverlapDutyCycle': 0.1,
            'globalInhibition': True
        }
    }, {
        'generalTM': {
            'activationThreshold': 4,
            'cellsPerColumn': 32,
            'connectedPermanence': 0.5,
            'minThreshold': 4,
            'potentialRadius': 0.0,
            'permanenceDecrement': 0.0,
            'initialPermanence': 0.4,
            'permanenceIncrement': 0.3240907051682719,
            'maxNewSynapseCount': 4
        },
        'actionTM': {
            'activationThreshold': 4,
            'cellsPerColumn': 32,
            'connectedPermanence': 0.5,
            'minThreshold': 4,
            'potentialRadius': 0.0,
            'permanenceIncrement': 0.05,
            'initialPermanence': 0.6519654776495574,
            'permanenceDecrement': 0.05,
            'maxNewSynapseCount': 4
        },
        'wordTM': {
            'activationThreshold': 4,
            'cellsPerColumn': 32,
            'connectedPermanence': 0.5,
            'minThreshold': 4,
            'potentialRadius': 0.0,
            'permanenceIncrement': 0.05,
            'initialPermanence': 0.4,
            'permanenceDecrement': 0.05,
            'maxNewSynapseCount': 4
        },
        'actionSP': {
            'stimulusThreshold': 0,
            'synPermInactiveDec': 0.1,
            'localAreaDensity': -1.0,
            'maxBoost': 3,
            'potentialRadius': 12,
            'dutyCyclePeriod': 10,
            'synPermConnected': 0.1,
            'synPermActiveInc': 0.1,
            'potentialPct': 0.5,
            'wrapAround': True,
            'minPctOverlapDutyCycle': 0.1,
            'globalInhibition': True
        },
        'wordSP': {
            'stimulusThreshold': 0,
            'potentialRadius': 12,
            'localAreaDensity': -1.0,
            'maxBoost': 3,
            'synPermInactiveDec': 0.1,
            'dutyCyclePeriod': 10,
            'synPermConnected': 0.1869889134299891,
            'synPermActiveInc': 0.1,
            'potentialPct': 0.5,
            'wrapAround': True,
            'minPctOverlapDutyCycle': 0.1,
            'globalInhibition': True
        }
    }
]
