nonOptimParams = {'trainMaxTime': 30, 'generalSP___columnDimensions': (1440,), 'testsMaxTime': 15, 'generalSP___spVerbosity': 0, 'generalTM___seed': 42, 'generalTM___columnDimensions': (1440,), 'generalSP___localAreaDensity': -1.0, 'generalSP___inputDimensions': 297, 'generalSP___seed': 42, 'model': <Learning.LearningModels.OneLevelExpModel object at 0x7ffd4b9978d0>, 'trainIterations': 50}
Best Scores: [67.36, 62.5, 62.15]
bestFindings:
[
Parameter(
    name='generalTM___cellsPerColumn',
    dataType='int',
    value=64,
    minVal=1,
    maxVal=500,
    maxChange=15,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___activationThreshold',
    dataType='int',
    value=1,
    minVal=1,
    maxVal=499,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___initialPermanence',
    dataType='float',
    value=0.22382208699,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___connectedPermanence',
    dataType='float',
    value=0.674714438958,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___minThreshold',
    dataType='int',
    value=4,
    minVal=1,
    maxVal=100,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___maxNewSynapseCount',
    dataType='int',
    value=4,
    minVal=1,
    maxVal=20,
    maxChange=3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceIncrement',
    dataType='float',
    value=0.117671359444,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceDecrement',
    dataType='float',
    value=1.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___predictedSegmentDecrement',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialRadius',
    dataType='int',
    value=297,
    minVal=1,
    maxVal=297,
    maxChange=29,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialPct',
    dataType='float',
    value=0.726248028695,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___globalInhibition',
    dataType='bool',
    value=True,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
), 
Parameter(
    name='generalSP___numActiveColumnsPerInhArea',
    dataType='float',
    value=4.0,
    minVal=0.0,
    maxVal=297,
    maxChange=2.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___stimulusThreshold',
    dataType='int',
    value=2,
    minVal=0,
    maxVal=10,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermInactiveDec',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermActiveInc',
    dataType='float',
    value=0.1,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermConnected',
    dataType='float',
    value=0.314036861165,
    minVal=0.0,
    maxVal=0.9,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctOverlapDutyCycle',
    dataType='float',
    value=0.302204519404,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctActiveDutyCycle',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___dutyCyclePeriod',
    dataType='int',
    value=9,
    minVal=1,
    maxVal=200,
    maxChange=10,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___maxBoost',
    dataType='float',
    value=1.0,
    minVal=1.0,
    maxVal=50.0,
    maxChange=4.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___wrapAround',
    dataType='bool',
    value=True,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
)]
[
Parameter(
    name='generalTM___cellsPerColumn',
    dataType='int',
    value=64,
    minVal=1,
    maxVal=500,
    maxChange=15,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___activationThreshold',
    dataType='int',
    value=1,
    minVal=1,
    maxVal=499,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___initialPermanence',
    dataType='float',
    value=0.22382208699,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___connectedPermanence',
    dataType='float',
    value=0.518188131733,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___minThreshold',
    dataType='int',
    value=1,
    minVal=1,
    maxVal=100,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___maxNewSynapseCount',
    dataType='int',
    value=4,
    minVal=1,
    maxVal=20,
    maxChange=3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceIncrement',
    dataType='float',
    value=0.117671359444,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceDecrement',
    dataType='float',
    value=1.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___predictedSegmentDecrement',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialRadius',
    dataType='int',
    value=297,
    minVal=1,
    maxVal=297,
    maxChange=29,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialPct',
    dataType='float',
    value=0.726248028695,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___globalInhibition',
    dataType='bool',
    value=True,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
), 
Parameter(
    name='generalSP___numActiveColumnsPerInhArea',
    dataType='float',
    value=4.0,
    minVal=0.0,
    maxVal=297,
    maxChange=2.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___stimulusThreshold',
    dataType='int',
    value=2,
    minVal=0,
    maxVal=10,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermInactiveDec',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermActiveInc',
    dataType='float',
    value=0.1,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermConnected',
    dataType='float',
    value=0.163485726079,
    minVal=0.0,
    maxVal=0.9,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctOverlapDutyCycle',
    dataType='float',
    value=0.218972868981,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctActiveDutyCycle',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___dutyCyclePeriod',
    dataType='int',
    value=15,
    minVal=1,
    maxVal=200,
    maxChange=10,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___maxBoost',
    dataType='float',
    value=1.0,
    minVal=1.0,
    maxVal=50.0,
    maxChange=4.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___wrapAround',
    dataType='bool',
    value=True,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
)]
[
Parameter(
    name='generalTM___cellsPerColumn',
    dataType='int',
    value=64,
    minVal=1,
    maxVal=500,
    maxChange=15,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___activationThreshold',
    dataType='int',
    value=1,
    minVal=1,
    maxVal=499,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___initialPermanence',
    dataType='float',
    value=0.22382208699,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___connectedPermanence',
    dataType='float',
    value=0.674714438958,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___minThreshold',
    dataType='int',
    value=1,
    minVal=1,
    maxVal=100,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___maxNewSynapseCount',
    dataType='int',
    value=4,
    minVal=1,
    maxVal=20,
    maxChange=3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceIncrement',
    dataType='float',
    value=0.291122264155,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceDecrement',
    dataType='float',
    value=1.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___predictedSegmentDecrement',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialRadius',
    dataType='int',
    value=297,
    minVal=1,
    maxVal=297,
    maxChange=29,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialPct',
    dataType='float',
    value=0.726248028695,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___globalInhibition',
    dataType='bool',
    value=True,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
), 
Parameter(
    name='generalSP___numActiveColumnsPerInhArea',
    dataType='float',
    value=4.0,
    minVal=0.0,
    maxVal=297,
    maxChange=2.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___stimulusThreshold',
    dataType='int',
    value=2,
    minVal=0,
    maxVal=10,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermInactiveDec',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermActiveInc',
    dataType='float',
    value=0.1,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermConnected',
    dataType='float',
    value=0.183390868165,
    minVal=0.0,
    maxVal=0.9,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctOverlapDutyCycle',
    dataType='float',
    value=0.218972868981,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctActiveDutyCycle',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___dutyCyclePeriod',
    dataType='int',
    value=15,
    minVal=1,
    maxVal=200,
    maxChange=10,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___maxBoost',
    dataType='float',
    value=1.0,
    minVal=1.0,
    maxVal=50.0,
    maxChange=4.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___wrapAround',
    dataType='bool',
    value=True,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
)]
