nonOptimParams = {'trainMaxTime': 30, 'generalSP___columnDimensions': (1440,), 'testsMaxTime': 15, 'generalSP___spVerbosity': 0, 'generalTM___seed': 42, 'generalTM___columnDimensions': (1440,), 'generalSP___localAreaDensity': -1.0, 'generalSP___inputDimensions': 297, 'generalSP___seed': 42, 'model': <Learning.LearningModels.OneLevelExpModel object at 0x7ff64ab61990>, 'trainIterations': 50}
bestFindings:
[
Parameter(
    name='generalTM___cellsPerColumn',
    dataType='int',
    value=64,
    minVal=1,
    maxVal=500,
    maxChange=15,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___activationThreshold',
    dataType='int',
    value=1,
    minVal=1,
    maxVal=499,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___initialPermanence',
    dataType='float',
    value=0.22382208699,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___connectedPermanence',
    dataType='float',
    value=0.674714438958,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___minThreshold',
    dataType='int',
    value=4,
    minVal=1,
    maxVal=100,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___maxNewSynapseCount',
    dataType='int',
    value=4,
    minVal=1,
    maxVal=20,
    maxChange=3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceIncrement',
    dataType='float',
    value=0.117671359444,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceDecrement',
    dataType='float',
    value=0.52118115778,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___predictedSegmentDecrement',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialRadius',
    dataType='int',
    value=297,
    minVal=1,
    maxVal=297,
    maxChange=29,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialPct',
    dataType='float',
    value=0.726248028695,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___globalInhibition',
    dataType='bool',
    value=True,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
), 
Parameter(
    name='generalSP___numActiveColumnsPerInhArea',
    dataType='float',
    value=4.0,
    minVal=0.0,
    maxVal=297,
    maxChange=2.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___stimulusThreshold',
    dataType='int',
    value=0,
    minVal=0,
    maxVal=10,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermInactiveDec',
    dataType='float',
    value=0.121754178434,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermActiveInc',
    dataType='float',
    value=0.1,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermConnected',
    dataType='float',
    value=0.107148493503,
    minVal=0.0,
    maxVal=0.9,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctOverlapDutyCycle',
    dataType='float',
    value=0.137190887797,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctActiveDutyCycle',
    dataType='float',
    value=0.1,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___dutyCyclePeriod',
    dataType='int',
    value=15,
    minVal=1,
    maxVal=200,
    maxChange=10,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___maxBoost',
    dataType='float',
    value=1.0,
    minVal=1.0,
    maxVal=50.0,
    maxChange=4.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___wrapAround',
    dataType='bool',
    value=True,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
)]
[
Parameter(
    name='generalTM___cellsPerColumn',
    dataType='int',
    value=64,
    minVal=1,
    maxVal=500,
    maxChange=15,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___activationThreshold',
    dataType='int',
    value=1,
    minVal=1,
    maxVal=499,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___initialPermanence',
    dataType='float',
    value=0.22382208699,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___connectedPermanence',
    dataType='float',
    value=0.674714438958,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___minThreshold',
    dataType='int',
    value=1,
    minVal=1,
    maxVal=100,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___maxNewSynapseCount',
    dataType='int',
    value=4,
    minVal=1,
    maxVal=20,
    maxChange=3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceIncrement',
    dataType='float',
    value=0.117671359444,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceDecrement',
    dataType='float',
    value=0.52118115778,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___predictedSegmentDecrement',
    dataType='float',
    value=0.152051275701,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialRadius',
    dataType='int',
    value=297,
    minVal=1,
    maxVal=297,
    maxChange=29,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialPct',
    dataType='float',
    value=0.726248028695,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___globalInhibition',
    dataType='bool',
    value=True,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
), 
Parameter(
    name='generalSP___numActiveColumnsPerInhArea',
    dataType='float',
    value=2.29904373997,
    minVal=0.0,
    maxVal=297,
    maxChange=2.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___stimulusThreshold',
    dataType='int',
    value=0,
    minVal=0,
    maxVal=10,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermInactiveDec',
    dataType='float',
    value=0.121754178434,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermActiveInc',
    dataType='float',
    value=0.1,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermConnected',
    dataType='float',
    value=0.298153901101,
    minVal=0.0,
    maxVal=0.9,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctOverlapDutyCycle',
    dataType='float',
    value=0.0292024318453,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctActiveDutyCycle',
    dataType='float',
    value=0.195483845504,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___dutyCyclePeriod',
    dataType='int',
    value=15,
    minVal=1,
    maxVal=200,
    maxChange=10,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___maxBoost',
    dataType='float',
    value=1.0,
    minVal=1.0,
    maxVal=50.0,
    maxChange=4.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___wrapAround',
    dataType='bool',
    value=False,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
)]
[
Parameter(
    name='generalTM___cellsPerColumn',
    dataType='int',
    value=64,
    minVal=1,
    maxVal=500,
    maxChange=15,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___activationThreshold',
    dataType='int',
    value=1,
    minVal=1,
    maxVal=499,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___initialPermanence',
    dataType='float',
    value=0.0451223491785,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___connectedPermanence',
    dataType='float',
    value=0.467832351034,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___minThreshold',
    dataType='int',
    value=4,
    minVal=1,
    maxVal=100,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___maxNewSynapseCount',
    dataType='int',
    value=4,
    minVal=1,
    maxVal=20,
    maxChange=3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceIncrement',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___permanenceDecrement',
    dataType='float',
    value=0.52118115778,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalTM___predictedSegmentDecrement',
    dataType='float',
    value=0.0,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialRadius',
    dataType='int',
    value=279,
    minVal=1,
    maxVal=297,
    maxChange=29,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___potentialPct',
    dataType='float',
    value=0.716394500313,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___globalInhibition',
    dataType='bool',
    value=True,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
), 
Parameter(
    name='generalSP___numActiveColumnsPerInhArea',
    dataType='float',
    value=4.0,
    minVal=0.0,
    maxVal=297,
    maxChange=2.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___stimulusThreshold',
    dataType='int',
    value=5,
    minVal=0,
    maxVal=10,
    maxChange=5,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermInactiveDec',
    dataType='float',
    value=0.0724532735555,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermActiveInc',
    dataType='float',
    value=0.1,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___synPermConnected',
    dataType='float',
    value=0.107148493503,
    minVal=0.0,
    maxVal=0.9,
    maxChange=0.3,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctOverlapDutyCycle',
    dataType='float',
    value=0.0208367778561,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___minPctActiveDutyCycle',
    dataType='float',
    value=0.1,
    minVal=0.0,
    maxVal=1.0,
    maxChange=0.2,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___dutyCyclePeriod',
    dataType='int',
    value=13,
    minVal=1,
    maxVal=200,
    maxChange=10,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___maxBoost',
    dataType='float',
    value=1.0,
    minVal=1.0,
    maxVal=50.0,
    maxChange=4.0,
    mutationProb=1.0
), 
Parameter(
    name='generalSP___wrapAround',
    dataType='bool',
    value=False,
    minVal=0,
    maxVal=9223372036854775807,
    maxChange=9223372036854775807,
    mutationProb=0.5
)]
