"""
Automatically generated Training Data Set
"""

trainingData = (
    (['move', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['move', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['move', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['move', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['move', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['move', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['move', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['move', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['move', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['move', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['move', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['move', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['please', 'move', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['go', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['go', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['go', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['go', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['go', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['go', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['go', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['go', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['go', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['go', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['go', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['go', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['go', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['go', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['go', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['turn', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['turn', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['turn', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['turn', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['turn', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['turn', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['turn', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['turn', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['turn', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['turn', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['turn', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['turn', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['turn', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['turn', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['head', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['head', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['head', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['head', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['head', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['head', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['head', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['head', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['head', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['head', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['head', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['head', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['head', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['move', 'your', 'bones', '!'], ['bailar-event', 'nothing-event']),
    (['everybody', 'dance', 'now'], ['bailar-event', 'nothing-event']),
    (['show', 'me', 'what', 'you', 'got'], ['bailar-event', 'nothing-event']),
    (['shake', 'your', 'moneymaker'], ['bailar-event', 'nothing-event']),
    (['get', 'your', 'groove', 'on'], ['bailar-event', 'nothing-event']),
    (['cut', 'a', 'rug'], ['bailar-event', 'nothing-event']),
    (['may', 'I', 'have', 'this', 'dance', '?'], ['bailar-event', 'nothing-event']),
    (['boogie'], ['bailar-event', 'nothing-event']),
    (['boogie', 'down'], ['bailar-event', 'nothing-event']),
    (['kick', 'up', 'your', 'heels'], ['bailar-event', 'nothing-event']),
    (['could', 'you', 'put', 'the', 'hat', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'put', 'that', 'object', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'put', 'that', 'thingy', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'please', 'put', 'the', 'hat', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'please', 'put', 'that', 'object', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'please', 'put', 'that', 'thingy', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['put', 'that', 'object', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'that', 'thingy', 'on'], ['recoger-event', 'nothing-event']),
    (['please', 'put', 'that', 'object', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on', 'please'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on', 'please'], ['recoger-event', 'nothing-event']),
    (['grab', 'the', 'hat'], ['recoger-event', 'nothing-event']),
    (['grab', 'that', 'object'], ['recoger-event', 'nothing-event']),
    (['grab', 'that', 'thingy'], ['recoger-event', 'nothing-event']),
    (['grab', 'the', 'hat', 'please'], ['recoger-event', 'nothing-event']),
    (['grab', 'that', 'object', 'please'], ['recoger-event', 'nothing-event']),
    (['grab', 'that', 'thingy', 'please'], ['recoger-event', 'nothing-event']),

)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['right', 'booty', 'may', 'moneymaker', 'show', 'dance', 'please', 'move', 'it', 'down', 'bones', 'want', 'shake', 'go', 'your', '!', 'what', 'cut', 'thing', 'west', 'boogie', 'downwards', 'bust', 'to', 'that', 'got', 'you', 'east', 'hat', '?', 'everybody', 'head', 'towards', 'north', 'get', 'I', 'object', 'rug', 'heels', 'a', 'kick', 'put', 'now', 'grab', 'upwards', 'me', 'on', 'thingy', 'this', 'could', 'up', 'turn', 'can', 'have', 'the', 'groove', 'south', 'left']), set(['derecha-event', 'mover-event', 'nothing-event', 'bailar-event', 'recoger-event', 'izquierda-event', 'arriba-event', 'abajo-event'])]