"""
Automatically generated Training Data Set
"""

trainingData = (
    (['move', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['move', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['move', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['move', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['move', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['move', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['move', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['move', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['move', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['move', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['move', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['move', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['move', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['move', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['move', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['move', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['please', 'move', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['please', 'move', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['please', 'move', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['please', 'move', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['can', 'you', 'please', 'move', 'it', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['go', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['go', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['go', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['go', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['go', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['go', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['go', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['go', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['go', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['go', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['go', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['go', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['go', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['go', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['go', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['go', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['turn', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['turn', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['turn', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['turn', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['turn', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['turn', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['turn', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['turn', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['turn', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['turn', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['turn', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['turn', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['turn', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['turn', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['turn', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['turn', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['head', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['head', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['head', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['head', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['head', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['head', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['head', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['head', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['head', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['head', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['head', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['head', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['head', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['head', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['head', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['head', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'to', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['move', 'your', 'bones', '!'], ['bailar-event', 'nothing-event']),
    (['dance', 'now'], ['bailar-event', 'nothing-event']),
    (['everybody', 'dance', 'now'], ['bailar-event', 'nothing-event']),
    (['show', 'me', 'what', 'you', 'got'], ['bailar-event', 'nothing-event']),
    (['shake', 'your', 'moneymaker'], ['bailar-event', 'nothing-event']),
    (['shake', 'your', 'groove', 'thing'], ['bailar-event', 'nothing-event']),
    (['shake', 'your', 'booty'], ['bailar-event', 'nothing-event']),
    (['get', 'down'], ['bailar-event', 'nothing-event']),
    (['bust', 'a', 'move'], ['bailar-event', 'nothing-event']),
    (['get', 'your', 'groove', 'on'], ['bailar-event', 'nothing-event']),
    (['cut', 'a', 'rug'], ['bailar-event', 'nothing-event']),
    (['may', 'I', 'have', 'this', 'dance', '?'], ['bailar-event', 'nothing-event']),
    (['boogie'], ['bailar-event', 'nothing-event']),
    (['boogie', 'down'], ['bailar-event', 'nothing-event']),
    (['kick', 'up', 'your', 'heels'], ['bailar-event', 'nothing-event']),
    (['recoge', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['recoge', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['recoge', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['recoge', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['recoge', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['alza', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['alza', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['levanta', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['levanta', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['ponte', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['ponte', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),

)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['el', 'right', 'booty', 'may', 'moneymaker', 'show', 'dance', 'please', 'move', 'por', 'it', 'down', 'bones', 'levantalo', 'want', 'shake', 'go', 'ahi', 'your', 'levanta', 'esta', '!', 'what', 'cut', 'objeto', 'thing', 'west', 'boogie', 'downwards', 'bust', 'to', 'got', 'you', 'east', 'favor', '?', 'cachucha', 'everybody', 'head', 'towards', 'north', 'get', 'I', 'rug', 'recoge', 'alzalo', 'heels', 'que', 'a', 'pontelo', 'kick', 'now', 'upwards', 'me', 'on', 'ponte', 'this', 'alza', 'could', 'la', 'up', 'lo', 'turn', 'can', 'have', 'sombrero', 'the', 'recogelo', 'groove', 'south', 'left']), set(['derecha-event', 'mover-event', 'nothing-event', 'bailar-event', 'recoger-event', 'izquierda-event', 'arriba-event', 'abajo-event'])]