"""
Automatically generated Training Data Set for the Movement actions
"""

trainingData = (
    (['mover', 'hacia', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['mover', 'hacia', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['mover', 'hacia', 'arriba'], ['action-mover', 'action-arriba']),
    (['mover', 'hacia', 'abajo'], ['action-mover', 'action-abajo']),
    (['mover', 'hacia', 'este'], ['action-mover', 'action-derecha']),
    (['mover', 'hacia', 'oeste'], ['action-mover', 'action-izquierda']),
    (['mover', 'hacia', 'norte'], ['action-mover', 'action-arriba']),
    (['mover', 'hacia', 'sur'], ['action-mover', 'action-abajo']),
    (['mover', 'a', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['mover', 'a', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['mover', 'a', 'arriba'], ['action-mover', 'action-arriba']),
    (['mover', 'a', 'abajo'], ['action-mover', 'action-abajo']),
    (['mover', 'a', 'este'], ['action-mover', 'action-derecha']),
    (['mover', 'a', 'oeste'], ['action-mover', 'action-izquierda']),
    (['mover', 'a', 'norte'], ['action-mover', 'action-arriba']),
    (['mover', 'a', 'sur'], ['action-mover', 'action-abajo']),
    (['mover', 'para', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['mover', 'para', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['mover', 'para', 'arriba'], ['action-mover', 'action-arriba']),
    (['mover', 'para', 'abajo'], ['action-mover', 'action-abajo']),
    (['mover', 'para', 'este'], ['action-mover', 'action-derecha']),
    (['mover', 'para', 'oeste'], ['action-mover', 'action-izquierda']),
    (['mover', 'para', 'norte'], ['action-mover', 'action-arriba']),
    (['mover', 'para', 'sur'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'hacia', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'hacia', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'hacia', 'arriba'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'hacia', 'abajo'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'hacia', 'este'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'hacia', 'oeste'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'hacia', 'norte'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'hacia', 'sur'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'a', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'a', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'a', 'arriba'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'a', 'abajo'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'a', 'este'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'a', 'oeste'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'a', 'norte'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'a', 'sur'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'para', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'para', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'para', 'arriba'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'para', 'abajo'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'para', 'este'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'para', 'oeste'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'para', 'norte'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'para', 'sur'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'arriba'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'abajo'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'este'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'oeste'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'norte'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'sur'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'arriba'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'abajo'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'este'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'oeste'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'norte'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'sur'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'arriba'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'abajo'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'este'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'oeste'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'norte'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'sur'], ['action-mover', 'action-abajo']),
    (['moverse', 'hacia', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['moverse', 'hacia', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['moverse', 'hacia', 'arriba'], ['action-mover', 'action-arriba']),
    (['moverse', 'hacia', 'abajo'], ['action-mover', 'action-abajo']),
    (['moverse', 'hacia', 'este'], ['action-mover', 'action-derecha']),
    (['moverse', 'hacia', 'oeste'], ['action-mover', 'action-izquierda']),
    (['moverse', 'hacia', 'norte'], ['action-mover', 'action-arriba']),
    (['moverse', 'hacia', 'sur'], ['action-mover', 'action-abajo']),
    (['moverse', 'a', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['moverse', 'a', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['moverse', 'a', 'arriba'], ['action-mover', 'action-arriba']),
    (['moverse', 'a', 'abajo'], ['action-mover', 'action-abajo']),
    (['moverse', 'a', 'este'], ['action-mover', 'action-derecha']),
    (['moverse', 'a', 'oeste'], ['action-mover', 'action-izquierda']),
    (['moverse', 'a', 'norte'], ['action-mover', 'action-arriba']),
    (['moverse', 'a', 'sur'], ['action-mover', 'action-abajo']),
    (['moverse', 'para', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['moverse', 'para', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['moverse', 'para', 'arriba'], ['action-mover', 'action-arriba']),
    (['moverse', 'para', 'abajo'], ['action-mover', 'action-abajo']),
    (['moverse', 'para', 'este'], ['action-mover', 'action-derecha']),
    (['moverse', 'para', 'oeste'], ['action-mover', 'action-izquierda']),
    (['moverse', 'para', 'norte'], ['action-mover', 'action-arriba']),
    (['moverse', 'para', 'sur'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'la', 'derecha', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'la', 'izquierda', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'arriba', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'abajo', '?'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'este', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'oeste', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'norte', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'sur', '?'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'la', 'derecha', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'la', 'izquierda', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'arriba', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'abajo', '?'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'este', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'oeste', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'norte', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'sur', '?'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'la', 'derecha', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'la', 'izquierda', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'arriba', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'abajo', '?'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'este', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'oeste', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'norte', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'sur', '?'], ['action-mover', 'action-abajo']),
    (['muevete', 'hacia', 'la', 'derecha', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'hacia', 'la', 'izquierda', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'hacia', 'arriba', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'hacia', 'abajo', 'por', 'favor'], ['action-mover', 'action-abajo']),
    (['muevete', 'hacia', 'este', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'hacia', 'oeste', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'hacia', 'norte', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'hacia', 'sur', 'por', 'favor'], ['action-mover', 'action-abajo']),
    (['muevete', 'a', 'la', 'derecha', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'a', 'la', 'izquierda', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'a', 'arriba', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'a', 'abajo', 'por', 'favor'], ['action-mover', 'action-abajo']),
    (['muevete', 'a', 'este', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'a', 'oeste', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'a', 'norte', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'a', 'sur', 'por', 'favor'], ['action-mover', 'action-abajo']),
    (['muevete', 'para', 'la', 'derecha', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'para', 'la', 'izquierda', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'para', 'arriba', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'para', 'abajo', 'por', 'favor'], ['action-mover', 'action-abajo']),
    (['muevete', 'para', 'este', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'para', 'oeste', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'para', 'norte', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'para', 'sur', 'por', 'favor'], ['action-mover', 'action-abajo'])
)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['este', 'por', 'hacia', 'mover', 'quiero', 'muevete', 'la', 'moverse', 'derecha', 'favor', 'arriba', 'sur', 'te', '\xbf', 'podrias', 'para', 'norte', 'abajo', 'que', 'oeste', 'a', 'izquierda', '?', 'muevas', 'moverlo']), set(['action-izquierda', 'action-mover', 'action-derecha', 'action-abajo', 'action-arriba'])]