"""
Automatically generated Training Data Set for the Movement actions
"""

trainingData = (
    (['mover', 'hacia', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['mover', 'hacia', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['mover', 'hacia', 'arriba'], ['action-mover', 'action-arriba']),
    (['mover', 'hacia', 'abajo'], ['action-mover', 'action-abajo']),
    (['mover', 'a', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['mover', 'a', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['mover', 'a', 'arriba'], ['action-mover', 'action-arriba']),
    (['mover', 'a', 'abajo'], ['action-mover', 'action-abajo']),
    (['mover', 'para', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['mover', 'para', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['mover', 'para', 'arriba'], ['action-mover', 'action-arriba']),
    (['mover', 'para', 'abajo'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'hacia', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'hacia', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'hacia', 'arriba'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'hacia', 'abajo'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'a', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'a', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'a', 'arriba'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'a', 'abajo'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'para', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'para', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'para', 'arriba'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'para', 'abajo'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'arriba'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'abajo'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'arriba'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'abajo'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'arriba'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'abajo'], ['action-mover', 'action-abajo']),
    (['moverse', 'hacia', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['moverse', 'hacia', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['moverse', 'hacia', 'arriba'], ['action-mover', 'action-arriba']),
    (['moverse', 'hacia', 'abajo'], ['action-mover', 'action-abajo']),
    (['moverse', 'a', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['moverse', 'a', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['moverse', 'a', 'arriba'], ['action-mover', 'action-arriba']),
    (['moverse', 'a', 'abajo'], ['action-mover', 'action-abajo']),
    (['moverse', 'para', 'la', 'derecha'], ['action-mover', 'action-derecha']),
    (['moverse', 'para', 'la', 'izquierda'], ['action-mover', 'action-izquierda']),
    (['moverse', 'para', 'arriba'], ['action-mover', 'action-arriba']),
    (['moverse', 'para', 'abajo'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'la', 'derecha', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'la', 'izquierda', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'arriba', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'abajo', '?'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'la', 'derecha', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'la', 'izquierda', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'arriba', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'a', 'abajo', '?'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'la', 'derecha', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'la', 'izquierda', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'arriba', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'abajo', '?'], ['action-mover', 'action-abajo']),
    (['muevete', 'hacia', 'la', 'derecha', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'hacia', 'la', 'izquierda', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'hacia', 'arriba', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'hacia', 'abajo', 'por', 'favor'], ['action-mover', 'action-abajo']),
    (['muevete', 'a', 'la', 'derecha', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'a', 'la', 'izquierda', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'a', 'arriba', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'a', 'abajo', 'por', 'favor'], ['action-mover', 'action-abajo']),
    (['muevete', 'para', 'la', 'derecha', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'para', 'la', 'izquierda', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'para', 'arriba', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'para', 'abajo', 'por', 'favor'], ['action-mover', 'action-abajo']),
    (['mover', 'hacia', 'el', 'este'], ['action-mover', 'action-derecha']),
    (['mover', 'hacia', 'el', 'oeste'], ['action-mover', 'action-izquierda']),
    (['mover', 'hacia', 'el', 'norte'], ['action-mover', 'action-arriba']),
    (['mover', 'hacia', 'el', 'sur'], ['action-mover', 'action-abajo']),
    (['mover', 'al', 'este'], ['action-mover', 'action-derecha']),
    (['mover', 'al', 'oeste'], ['action-mover', 'action-izquierda']),
    (['mover', 'al', 'norte'], ['action-mover', 'action-arriba']),
    (['mover', 'al', 'sur'], ['action-mover', 'action-abajo']),
    (['mover', 'para', 'el', 'este'], ['action-mover', 'action-derecha']),
    (['mover', 'para', 'el', 'oeste'], ['action-mover', 'action-izquierda']),
    (['mover', 'para', 'el', 'norte'], ['action-mover', 'action-arriba']),
    (['mover', 'para', 'el', 'sur'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'este'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'oeste'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'norte'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'sur'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'para', 'el', 'este'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'para', 'el', 'oeste'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'para', 'el', 'norte'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'para', 'el', 'sur'], ['action-mover', 'action-abajo']),
    (['por', 'favor', 'mover', 'al', 'este'], ['action-mover', 'action-derecha']),
    (['por', 'favor', 'mover', 'al', 'oeste'], ['action-mover', 'action-izquierda']),
    (['por', 'favor', 'mover', 'al', 'norte'], ['action-mover', 'action-arriba']),
    (['por', 'favor', 'mover', 'al', 'sur'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'este'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'oeste'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'norte'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'sur'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'al', 'este'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'al', 'oeste'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'al', 'norte'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'al', 'sur'], ['action-mover', 'action-abajo']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'este'], ['action-mover', 'action-derecha']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'oeste'], ['action-mover', 'action-izquierda']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'norte'], ['action-mover', 'action-arriba']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'sur'], ['action-mover', 'action-abajo']),
    (['moverse', 'hacia', 'el', 'este'], ['action-mover', 'action-derecha']),
    (['moverse', 'hacia', 'el', 'oeste'], ['action-mover', 'action-izquierda']),
    (['moverse', 'hacia', 'el', 'norte'], ['action-mover', 'action-arriba']),
    (['moverse', 'hacia', 'el', 'sur'], ['action-mover', 'action-abajo']),
    (['moverse', 'al', 'este'], ['action-mover', 'action-derecha']),
    (['moverse', 'al', 'oeste'], ['action-mover', 'action-izquierda']),
    (['moverse', 'al', 'norte'], ['action-mover', 'action-arriba']),
    (['moverse', 'al', 'sur'], ['action-mover', 'action-abajo']),
    (['moverse', 'para', 'el', 'este'], ['action-mover', 'action-derecha']),
    (['moverse', 'para', 'el', 'oeste'], ['action-mover', 'action-izquierda']),
    (['moverse', 'para', 'el', 'norte'], ['action-mover', 'action-arriba']),
    (['moverse', 'para', 'el', 'sur'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'este', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'oeste', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'norte', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'sur', '?'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'el', 'este', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'el', 'oeste', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'el', 'norte', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'para', 'el', 'sur', '?'], ['action-mover', 'action-abajo']),
    (['\xbf', 'podrias', 'moverlo', 'al', 'este', '?'], ['action-mover', 'action-derecha']),
    (['\xbf', 'podrias', 'moverlo', 'al', 'oeste', '?'], ['action-mover', 'action-izquierda']),
    (['\xbf', 'podrias', 'moverlo', 'al', 'norte', '?'], ['action-mover', 'action-arriba']),
    (['\xbf', 'podrias', 'moverlo', 'al', 'sur', '?'], ['action-mover', 'action-abajo']),
    (['muevete', 'hacia', 'el', 'este', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'hacia', 'el', 'oeste', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'hacia', 'el', 'norte', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'hacia', 'el', 'sur', 'por', 'favor'], ['action-mover', 'action-abajo']),
    (['muevete', 'al', 'este', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'al', 'oeste', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'al', 'norte', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'al', 'sur', 'por', 'favor'], ['action-mover', 'action-abajo']),
    (['muevete', 'para', 'el', 'este', 'por', 'favor'], ['action-mover', 'action-derecha']),
    (['muevete', 'para', 'el', 'oeste', 'por', 'favor'], ['action-mover', 'action-izquierda']),
    (['muevete', 'para', 'el', 'norte', 'por', 'favor'], ['action-mover', 'action-arriba']),
    (['muevete', 'para', 'el', 'sur', 'por', 'favor'], ['action-mover', 'action-abajo'])
)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['el', 'este', 'por', 'al', 'hacia', 'mover', 'quiero', 'para', 'la', 'moverse', 'derecha', 'favor', 'arriba', 'sur', 'te', '?', 'podrias', 'muevete', 'norte', 'abajo', 'que', 'oeste', 'a', 'izquierda', '\xbf', 'muevas', 'moverlo']), set(['action-izquierda', 'action-mover', 'action-derecha', 'action-abajo', 'action-arriba'])]
