"""
Automatically generated Training Data Set for the Movement actions
"""

trainingData = (
    (['mover', 'hacia', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['mover', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['mover', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['mover', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['mover', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['mover', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['mover', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['mover', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['mover', 'a', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['mover', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['mover', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['mover', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['mover', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['mover', 'a', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['mover', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['mover', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['mover', 'para', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['mover', 'para', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['mover', 'para', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['mover', 'para', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['mover', 'para', 'arriba'], ['mover-event', 'arriba-event']),
    (['mover', 'para', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['mover', 'para', 'abajo'], ['mover-event', 'abajo-event']),
    (['mover', 'para', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'hacia', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'a', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'para', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'para', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'para', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'para', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'para', 'arriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'para', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'para', 'abajo'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'para', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'arriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'abajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'hacia', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['moverse', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['moverse', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['moverse', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'a', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['moverse', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['moverse', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'a', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['moverse', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'para', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'para', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['moverse', 'para', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['moverse', 'para', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'para', 'arriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'para', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['moverse', 'para', 'abajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'para', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'la', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'este', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'la', 'izquierda', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'arriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'abajo', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'la', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'este', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'la', 'izquierda', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'arriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'abajo', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'la', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'el', 'este', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'la', 'izquierda', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'el', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'arriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'el', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'abajo', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'el', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['muevete', 'hacia', 'la', 'derecha', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'hacia', 'el', 'este', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'hacia', 'la', 'izquierda', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'hacia', 'el', 'oeste', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'hacia', 'arriba', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'hacia', 'el', 'norte', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'hacia', 'abajo', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'hacia', 'el', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'a', 'la', 'derecha', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'a', 'el', 'este', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'a', 'la', 'izquierda', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'a', 'el', 'oeste', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'a', 'arriba', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'a', 'el', 'norte', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'a', 'abajo', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'a', 'el', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'para', 'la', 'derecha', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'para', 'el', 'este', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'para', 'la', 'izquierda', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'para', 'el', 'oeste', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'para', 'arriba', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'para', 'el', 'norte', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'para', 'abajo', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'para', 'el', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['hacia', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['hacia', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['hacia', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['hacia', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['hacia', 'arriba'], ['nothing-event', 'arriba-event']),
    (['hacia', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['hacia', 'abajo'], ['nothing-event', 'abajo-event']),
    (['hacia', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['a', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['a', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['a', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['a', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['a', 'arriba'], ['nothing-event', 'arriba-event']),
    (['a', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['a', 'abajo'], ['nothing-event', 'abajo-event']),
    (['a', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['para', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['para', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['para', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['para', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['para', 'arriba'], ['nothing-event', 'arriba-event']),
    (['para', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['para', 'abajo'], ['nothing-event', 'abajo-event']),
    (['para', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['por', 'favor', 'hacia', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['por', 'favor', 'hacia', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['por', 'favor', 'hacia', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['por', 'favor', 'hacia', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['por', 'favor', 'hacia', 'arriba'], ['nothing-event', 'arriba-event']),
    (['por', 'favor', 'hacia', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['por', 'favor', 'hacia', 'abajo'], ['nothing-event', 'abajo-event']),
    (['por', 'favor', 'hacia', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['por', 'favor', 'a', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['por', 'favor', 'a', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['por', 'favor', 'a', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['por', 'favor', 'a', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['por', 'favor', 'a', 'arriba'], ['nothing-event', 'arriba-event']),
    (['por', 'favor', 'a', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['por', 'favor', 'a', 'abajo'], ['nothing-event', 'abajo-event']),
    (['por', 'favor', 'a', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['por', 'favor', 'para', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['por', 'favor', 'para', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['por', 'favor', 'para', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['por', 'favor', 'para', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['por', 'favor', 'para', 'arriba'], ['nothing-event', 'arriba-event']),
    (['por', 'favor', 'para', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['por', 'favor', 'para', 'abajo'], ['nothing-event', 'abajo-event']),
    (['por', 'favor', 'para', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'hacia', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'hacia', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'hacia', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'hacia', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'hacia', 'arriba'], ['nothing-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'hacia', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'hacia', 'abajo'], ['nothing-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'hacia', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'a', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'a', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'a', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'a', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'a', 'arriba'], ['nothing-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'a', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'a', 'abajo'], ['nothing-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'a', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'para', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'para', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'para', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'para', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'para', 'arriba'], ['nothing-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'para', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'para', 'abajo'], ['nothing-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'para', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['hacia', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['hacia', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['hacia', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['hacia', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['hacia', 'arriba'], ['nothing-event', 'arriba-event']),
    (['hacia', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['hacia', 'abajo'], ['nothing-event', 'abajo-event']),
    (['hacia', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['a', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['a', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['a', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['a', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['a', 'arriba'], ['nothing-event', 'arriba-event']),
    (['a', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['a', 'abajo'], ['nothing-event', 'abajo-event']),
    (['a', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['para', 'la', 'derecha'], ['nothing-event', 'derecha-event']),
    (['para', 'el', 'este'], ['nothing-event', 'derecha-event']),
    (['para', 'la', 'izquierda'], ['nothing-event', 'izquierda-event']),
    (['para', 'el', 'oeste'], ['nothing-event', 'izquierda-event']),
    (['para', 'arriba'], ['nothing-event', 'arriba-event']),
    (['para', 'el', 'norte'], ['nothing-event', 'arriba-event']),
    (['para', 'abajo'], ['nothing-event', 'abajo-event']),
    (['para', 'el', 'sur'], ['nothing-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'hacia', 'la', 'derecha', '?'], ['nothing-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'hacia', 'el', 'este', '?'], ['nothing-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'hacia', 'la', 'izquierda', '?'], ['nothing-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'hacia', 'el', 'oeste', '?'], ['nothing-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'hacia', 'arriba', '?'], ['nothing-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'hacia', 'el', 'norte', '?'], ['nothing-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'hacia', 'abajo', '?'], ['nothing-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'hacia', 'el', 'sur', '?'], ['nothing-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'a', 'la', 'derecha', '?'], ['nothing-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'a', 'el', 'este', '?'], ['nothing-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'a', 'la', 'izquierda', '?'], ['nothing-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'a', 'el', 'oeste', '?'], ['nothing-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'a', 'arriba', '?'], ['nothing-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'a', 'el', 'norte', '?'], ['nothing-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'a', 'abajo', '?'], ['nothing-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'a', 'el', 'sur', '?'], ['nothing-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'para', 'la', 'derecha', '?'], ['nothing-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'para', 'el', 'este', '?'], ['nothing-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'para', 'la', 'izquierda', '?'], ['nothing-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'para', 'el', 'oeste', '?'], ['nothing-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'para', 'arriba', '?'], ['nothing-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'para', 'el', 'norte', '?'], ['nothing-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'para', 'abajo', '?'], ['nothing-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'para', 'el', 'sur', '?'], ['nothing-event', 'abajo-event']),
    (['hacia', 'la', 'derecha', 'por', 'favor'], ['nothing-event', 'derecha-event']),
    (['hacia', 'el', 'este', 'por', 'favor'], ['nothing-event', 'derecha-event']),
    (['hacia', 'la', 'izquierda', 'por', 'favor'], ['nothing-event', 'izquierda-event']),
    (['hacia', 'el', 'oeste', 'por', 'favor'], ['nothing-event', 'izquierda-event']),
    (['hacia', 'arriba', 'por', 'favor'], ['nothing-event', 'arriba-event']),
    (['hacia', 'el', 'norte', 'por', 'favor'], ['nothing-event', 'arriba-event']),
    (['hacia', 'abajo', 'por', 'favor'], ['nothing-event', 'abajo-event']),
    (['hacia', 'el', 'sur', 'por', 'favor'], ['nothing-event', 'abajo-event']),
    (['a', 'la', 'derecha', 'por', 'favor'], ['nothing-event', 'derecha-event']),
    (['a', 'el', 'este', 'por', 'favor'], ['nothing-event', 'derecha-event']),
    (['a', 'la', 'izquierda', 'por', 'favor'], ['nothing-event', 'izquierda-event']),
    (['a', 'el', 'oeste', 'por', 'favor'], ['nothing-event', 'izquierda-event']),
    (['a', 'arriba', 'por', 'favor'], ['nothing-event', 'arriba-event']),
    (['a', 'el', 'norte', 'por', 'favor'], ['nothing-event', 'arriba-event']),
    (['a', 'abajo', 'por', 'favor'], ['nothing-event', 'abajo-event']),
    (['a', 'el', 'sur', 'por', 'favor'], ['nothing-event', 'abajo-event']),
    (['para', 'la', 'derecha', 'por', 'favor'], ['nothing-event', 'derecha-event']),
    (['para', 'el', 'este', 'por', 'favor'], ['nothing-event', 'derecha-event']),
    (['para', 'la', 'izquierda', 'por', 'favor'], ['nothing-event', 'izquierda-event']),
    (['para', 'el', 'oeste', 'por', 'favor'], ['nothing-event', 'izquierda-event']),
    (['para', 'arriba', 'por', 'favor'], ['nothing-event', 'arriba-event']),
    (['para', 'el', 'norte', 'por', 'favor'], ['nothing-event', 'arriba-event']),
    (['para', 'abajo', 'por', 'favor'], ['nothing-event', 'abajo-event']),
    (['para', 'el', 'sur', 'por', 'favor'], ['nothing-event', 'abajo-event'])
)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['este', 'el', 'por', 'hacia', 'mover', 'quiero', 'muevete', 'la', 'moverse', 'derecha', 'favor', 'arriba', 'sur', 'te', '?', 'podrias', 'para', 'norte', 'abajo', 'que', 'oeste', 'a', 'moverlo', 'izquierda', 'muevas', '\xc2\xbf']), set(['derecha-event', 'mover-event', 'nothing-event', 'izquierda-event', 'arriba-event', 'abajo-event'])]