"""
Automatically generated Training Data Set
"""

trainingData = (
    (['mover', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['mover', 'ael', 'este'], ['mover-event', 'derecha-event']),
    (['mover', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['mover', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['mover', 'aabajo'], ['mover-event', 'abajo-event']),
    (['mover', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['mover', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['mover', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['mover', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['mover', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['mover', 'haciael', 'norte'], ['mover-event', 'arriba-event']),
    (['mover', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['mover', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['mover', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['mover', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['mover', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['mover', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['mover', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['mover', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'ael', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'aarriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'haciael', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'ael', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'aarriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'aabajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'ael', 'este'], ['mover-event', 'derecha-event']),
    (['moverse', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['moverse', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'aarriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['moverse', 'aabajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['moverse', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['moverse', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['moverse', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['moverse', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['moverse', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'ala', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'ael', 'este', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'ala', 'izquierda', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'aarriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'ael', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'aabajo', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'ael', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'haciala', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'haciala', 'izquierda', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'haciaarriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'haciael', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'haciaabajo', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'haciael', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'parala', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'parael', 'este', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'parael', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'paraarriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'paraabajo', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'parael', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['muevete', 'ala', 'derecha', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'ael', 'este', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'ala', 'izquierda', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'ael', 'oeste', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'aarriba', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'ael', 'norte', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'aabajo', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'ael', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'haciala', 'derecha', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'haciael', 'este', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'haciala', 'izquierda', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'haciaarriba', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'haciael', 'norte', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'haciael', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'parala', 'derecha', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'parael', 'este', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'parala', 'izquierda', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'paraarriba', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'parael', 'norte', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'paraabajo', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'parael', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['ve', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ve', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['ve', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['ve', 'aabajo'], ['mover-event', 'abajo-event']),
    (['ve', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['ve', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['ve', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['ve', 'haciael', 'norte'], ['mover-event', 'arriba-event']),
    (['ve', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ve', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['ve', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['ve', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['ve', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['dirigite', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['dirigite', 'ael', 'este'], ['mover-event', 'derecha-event']),
    (['dirigite', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'aarriba'], ['mover-event', 'arriba-event']),
    (['dirigite', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['dirigite', 'aabajo'], ['mover-event', 'abajo-event']),
    (['dirigite', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['dirigite', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['dirigite', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['dirigite', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['dirigite', 'haciael', 'norte'], ['mover-event', 'arriba-event']),
    (['dirigite', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['dirigite', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['dirigite', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['dirigite', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['dirigite', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['dirigite', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['dirigite', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['dirigite', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['gira', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['gira', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['gira', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['gira', 'aarriba'], ['mover-event', 'arriba-event']),
    (['gira', 'aabajo'], ['mover-event', 'abajo-event']),
    (['gira', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['gira', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['gira', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['gira', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['gira', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['gira', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['gira', 'haciael', 'norte'], ['mover-event', 'arriba-event']),
    (['gira', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['gira', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['gira', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['gira', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['gira', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['gira', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['gira', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['gira', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['vuleve', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['vuleve', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['vuleve', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['vuleve', 'aarriba'], ['mover-event', 'arriba-event']),
    (['vuleve', 'aabajo'], ['mover-event', 'abajo-event']),
    (['vuleve', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['vuleve', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['vuleve', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['vuleve', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['vuleve', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['vuleve', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['vuleve', 'haciael', 'norte'], ['mover-event', 'arriba-event']),
    (['vuleve', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['vuleve', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['vuleve', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['vuleve', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['vuleve', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['vuleve', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['vuleve', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['ir', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ir', 'ael', 'este'], ['mover-event', 'derecha-event']),
    (['ir', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['ir', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['ir', 'aarriba'], ['mover-event', 'arriba-event']),
    (['ir', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['ir', 'aabajo'], ['mover-event', 'abajo-event']),
    (['ir', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['ir', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ir', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['ir', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['ir', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['ir', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['ir', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['ir', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['ir', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ir', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['ir', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['ir', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['ir', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['ir', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['ir', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['desplazate', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['desplazate', 'ael', 'este'], ['mover-event', 'derecha-event']),
    (['desplazate', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'aarriba'], ['mover-event', 'arriba-event']),
    (['desplazate', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['desplazate', 'aabajo'], ['mover-event', 'abajo-event']),
    (['desplazate', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['desplazate', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['desplazate', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['desplazate', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['desplazate', 'haciael', 'norte'], ['mover-event', 'arriba-event']),
    (['desplazate', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['desplazate', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['desplazate', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['desplazate', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['desplazate', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['desplazate', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['desplazate', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['desplazate', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['move', 'tothe', 'left'], ['mover-event', 'derecha-event']),
    (['move', 'tothe', 'east'], ['mover-event', 'derecha-event']),
    (['move', 'tothe', 'right'], ['mover-event', 'izquierda-event']),
    (['move', 'tothe', 'west'], ['mover-event', 'izquierda-event']),
    (['move', 'tothe', 'north'], ['mover-event', 'arriba-event']),
    (['move', 'todownwards'], ['mover-event', 'abajo-event']),
    (['move', 'tothe', 'south'], ['mover-event', 'abajo-event']),
    (['move', 'towardsthe', 'left'], ['mover-event', 'derecha-event']),
    (['move', 'towardsthe', 'east'], ['mover-event', 'derecha-event']),
    (['move', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['move', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['move', 'towardsthe', 'south'], ['mover-event', 'abajo-event']),
    (['please', 'move', 'tothe', 'left'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'tothe', 'right'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'tothe', 'west'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'toupwards'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'todownwards'], ['mover-event', 'abajo-event']),
    (['please', 'move', 'tothe', 'south'], ['mover-event', 'abajo-event']),
    (['please', 'move', 'towardsthe', 'left'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'towardsthe', 'east'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'towardsthe', 'south'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'tothe', 'east'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'tothe', 'right'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'tothe', 'west'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'toupwards'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'tothe', 'north'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'todownwards'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'tothe', 'south'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'towardsthe', 'left'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'towardsthe', 'east'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'towardsthe', 'right'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'towardsthe', 'west'], ['mover-event', 'izquierda-event']),
    (['I', 'want', 'you', 'to', 'move', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'towardsthe', 'south'], ['mover-event', 'abajo-event']),
    (['can', 'you', 'please', 'move', 'it', 'tothe', 'left'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'tothe', 'east'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'toupwards'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'tothe', 'north'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'todownwards'], ['mover-event', 'abajo-event']),
    (['can', 'you', 'please', 'move', 'it', 'tothe', 'south'], ['mover-event', 'abajo-event']),
    (['can', 'you', 'please', 'move', 'it', 'towardsthe', 'left'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'towardsthe', 'east'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'towardsthe', 'right'], ['mover-event', 'izquierda-event']),
    (['can', 'you', 'please', 'move', 'it', 'towardsthe', 'west'], ['mover-event', 'izquierda-event']),
    (['can', 'you', 'please', 'move', 'it', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'towardsthe', 'south'], ['mover-event', 'abajo-event']),
    (['go', 'tothe', 'left'], ['mover-event', 'derecha-event']),
    (['go', 'tothe', 'east'], ['mover-event', 'derecha-event']),
    (['go', 'tothe', 'right'], ['mover-event', 'izquierda-event']),
    (['go', 'tothe', 'west'], ['mover-event', 'izquierda-event']),
    (['go', 'toupwards'], ['mover-event', 'arriba-event']),
    (['go', 'tothe', 'north'], ['mover-event', 'arriba-event']),
    (['go', 'tothe', 'south'], ['mover-event', 'abajo-event']),
    (['go', 'towardsthe', 'east'], ['mover-event', 'derecha-event']),
    (['go', 'towardsthe', 'right'], ['mover-event', 'izquierda-event']),
    (['go', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['go', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['go', 'towardsthe', 'south'], ['mover-event', 'abajo-event']),
    (['turn', 'tothe', 'left'], ['mover-event', 'derecha-event']),
    (['turn', 'tothe', 'east'], ['mover-event', 'derecha-event']),
    (['turn', 'tothe', 'right'], ['mover-event', 'izquierda-event']),
    (['turn', 'tothe', 'north'], ['mover-event', 'arriba-event']),
    (['turn', 'tothe', 'south'], ['mover-event', 'abajo-event']),
    (['turn', 'towardsthe', 'left'], ['mover-event', 'derecha-event']),
    (['turn', 'towardsthe', 'east'], ['mover-event', 'derecha-event']),
    (['turn', 'towardsthe', 'west'], ['mover-event', 'izquierda-event']),
    (['turn', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['turn', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['turn', 'towardsthe', 'south'], ['mover-event', 'abajo-event']),
    (['head', 'tothe', 'left'], ['mover-event', 'derecha-event']),
    (['head', 'tothe', 'right'], ['mover-event', 'izquierda-event']),
    (['head', 'toupwards'], ['mover-event', 'arriba-event']),
    (['head', 'tothe', 'north'], ['mover-event', 'arriba-event']),
    (['head', 'todownwards'], ['mover-event', 'abajo-event']),
    (['head', 'tothe', 'south'], ['mover-event', 'abajo-event']),
    (['head', 'towardsthe', 'left'], ['mover-event', 'derecha-event']),
    (['head', 'towardsthe', 'east'], ['mover-event', 'derecha-event']),
    (['head', 'towardsthe', 'right'], ['mover-event', 'izquierda-event']),
    (['head', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['head', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['head', 'towardsthe', 'south'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'tothe', 'left'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'tothe', 'east'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'tothe', 'west'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'toupwards'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'todownwards'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'tothe', 'south'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'towardsthe', 'left'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'towardsthe', 'east'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'towardsthe', 'west'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'towardsthe', 'south'], ['mover-event', 'abajo-event']),
    (['a', 'mover', 'el', 'esqueleto'], ['bailar-event', 'nothing-event']),
    (['mueve', 'ese', 'esqueleto'], ['bailar-event', 'nothing-event']),
    (['\xc2\xa1', 'a', 'bailar', '!'], ['bailar-event', 'nothing-event']),
    (['baila'], ['bailar-event', 'nothing-event']),
    (['\xc2\xbf', 'bailas', '?'], ['bailar-event', 'nothing-event']),
    (['por', 'favor', ',', 'baila'], ['bailar-event', 'nothing-event']),
    (['no', 'pares', 'de', 'bailar'], ['bailar-event', 'nothing-event']),
    (['danza'], ['bailar-event', 'nothing-event']),
    (['quiero', 'ver', 'tus', 'movimientos'], ['bailar-event', 'nothing-event']),
    (['sabor'], ['bailar-event', 'nothing-event']),
    (['azotar', 'baldosa'], ['bailar-event', 'nothing-event']),
    (['baila', 'la', 'samba'], ['bailar-event', 'nothing-event']),
    (['dance', 'now'], ['bailar-event', 'nothing-event']),
    (['everybody', 'dance', 'now'], ['bailar-event', 'nothing-event']),
    (['shake', 'your', 'moneymaker'], ['bailar-event', 'nothing-event']),
    (['shake', 'your', 'groove', 'thing'], ['bailar-event', 'nothing-event']),
    (['shake', 'your', 'booty'], ['bailar-event', 'nothing-event']),
    (['get', 'down'], ['bailar-event', 'nothing-event']),
    (['get', 'your', 'groove', 'on'], ['bailar-event', 'nothing-event']),
    (['cut', 'a', 'rug'], ['bailar-event', 'nothing-event']),
    (['may', 'I', 'have', 'this', 'dance', '?'], ['bailar-event', 'nothing-event']),
    (['boogie'], ['bailar-event', 'nothing-event']),
    (['boogie', 'down'], ['bailar-event', 'nothing-event']),
    (['kick', 'up', 'your', 'heels'], ['bailar-event', 'nothing-event']),
    (['recoge', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['recoge', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['recoge', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['recoge', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['recoge', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['alza', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['levanta', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['levanta', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['ponte', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'put', 'the', 'hat', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'put', 'that', 'thingy', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'please', 'put', 'that', 'object', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'please', 'put', 'that', 'thingy', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['put', 'the', 'hat', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'that', 'object', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'that', 'thingy', 'on'], ['recoger-event', 'nothing-event']),
    (['please', 'put', 'the', 'hat', 'on'], ['recoger-event', 'nothing-event']),
    (['please', 'put', 'that', 'object', 'on'], ['recoger-event', 'nothing-event']),
    (['please', 'put', 'that', 'thingy', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on', 'please'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on', 'please'], ['recoger-event', 'nothing-event']),
    (['put', 'it', 'on', 'please'], ['recoger-event', 'nothing-event']),
    (['grab', 'the', 'hat'], ['recoger-event', 'nothing-event']),
    (['grab', 'that', 'object'], ['recoger-event', 'nothing-event']),
    (['grab', 'that', 'thingy'], ['recoger-event', 'nothing-event']),
    (['grab', 'that', 'object', 'please'], ['recoger-event', 'nothing-event']),
    (['grab', 'that', 'thingy', 'please'], ['recoger-event', 'nothing-event']),

)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['aarriba', 'dance', 'move', 'ala', 'shake', 'go', 'desplazate', 'quiero', 'ver', 'haciaabajo', 'moverse', 'lo', 'danza', 'baila', ',', 'bust', 'towardsthe', 'to', 'tiru', 'east', 'hat', 'kick', 'cachucha', 'get', 'toupwards', 'de', 'now', 'alza', 'titiru', 'muevas', 'have', 'grab', 'ael', 'el', 'right', 'booty', 'esqueleto', 'gira', 'parala', 'thing', 'tirutiru', 'what', 'dirigite', 'sombrero', 'boogie', 'please', 'todownwards', 'favor', 'ese', 'sur', 'got', '?', 'vamos', 'muevete', 'tus', 'rug', 'bailas', 'bailar', 'cut', 'samba', 'que', 'pontelo', 'put', 'on', '\xc2\xbf', 'sabor', 'vuleve', 'could', 'la', 'turn', 'bailamos', 'south', 'this', 'moneymaker', 'bailemos', 'ahi', 'por', 'azotar', 'down', 'levantalo', 'your', 'levanta', 'esta', 'everybody', 'pares', 'west', 'show', 'podrias', 'head', 'parael', 'north', 'that', 'paraarriba', 'aabajo', 'haciael', 'oeste', 'me', 'te', '\xc2\xa1', 'haciala', 'up', 'paraabajo', 'can', 'moverlo', 'groove', 'este', 've', 'ponte', 'ir', 'it', 'bones', 'want', 'haciaarriba', 'mover', '!', 'thingy', 'objeto', 'no', 'mueve', 'derecha', 'norte', 'baldosa', 'you', 'recogelo', 'may', 'heels', 'I', 'object', 'recoge', 'movimientos', 'a', 'izquierda', 'alzalo', 'tothe', 'the', 'left']), set(['derecha-event', 'mover-event', 'nothing-event', 'bailar-event', 'recoger-event', 'izquierda-event', 'arriba-event', 'abajo-event'])]