"""
Automatically generated Test Data Set
"""

trainingData = (
    (['mover', 'aarriba'], ['mover-event', 'arriba-event']),
    (['mover', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['mover', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['mover', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['mover', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'aabajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciael', 'norte'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'haciael', 'norte'], ['mover-event', 'arriba-event']),
    (['moverse', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'ael', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'haciael', 'este', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'haciael', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'parala', 'izquierda', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'parael', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['muevete', 'haciael', 'oeste', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'haciaabajo', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'parael', 'oeste', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['ve', 'ael', 'este'], ['mover-event', 'derecha-event']),
    (['ve', 'aarriba'], ['mover-event', 'arriba-event']),
    (['ve', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['ve', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ve', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['ve', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['ve', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['ve', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['ve', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['ve', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['ve', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['gira', 'ael', 'este'], ['mover-event', 'derecha-event']),
    (['gira', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['gira', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['gira', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['vuleve', 'ael', 'este'], ['mover-event', 'derecha-event']),
    (['vuleve', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['vuleve', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['vuleve', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['vuleve', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['ir', 'haciael', 'norte'], ['mover-event', 'arriba-event']),
    (['ir', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['move', 'toupwards'], ['mover-event', 'arriba-event']),
    (['move', 'towardsthe', 'right'], ['mover-event', 'izquierda-event']),
    (['move', 'towardsthe', 'west'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'tothe', 'east'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'tothe', 'north'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'towardsthe', 'right'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'towardsthe', 'west'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'tothe', 'left'], ['mover-event', 'derecha-event']),
    (['I', 'want', 'you', 'to', 'move', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'tothe', 'right'], ['mover-event', 'izquierda-event']),
    (['can', 'you', 'please', 'move', 'it', 'tothe', 'west'], ['mover-event', 'izquierda-event']),
    (['can', 'you', 'please', 'move', 'it', 'towardsthe', 'north'], ['mover-event', 'arriba-event']),
    (['go', 'todownwards'], ['mover-event', 'abajo-event']),
    (['go', 'towardsthe', 'left'], ['mover-event', 'derecha-event']),
    (['go', 'towardsthe', 'west'], ['mover-event', 'izquierda-event']),
    (['turn', 'tothe', 'west'], ['mover-event', 'izquierda-event']),
    (['turn', 'toupwards'], ['mover-event', 'arriba-event']),
    (['turn', 'todownwards'], ['mover-event', 'abajo-event']),
    (['turn', 'towardsthe', 'right'], ['mover-event', 'izquierda-event']),
    (['head', 'tothe', 'east'], ['mover-event', 'derecha-event']),
    (['head', 'tothe', 'west'], ['mover-event', 'izquierda-event']),
    (['head', 'towardsthe', 'west'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'tothe', 'right'], ['mover-event', 'izquierda-event']),
    (['could', 'you', 'head', 'tothe', 'north'], ['mover-event', 'arriba-event']),
    (['could', 'you', 'head', 'towardsthe', 'right'], ['mover-event', 'izquierda-event']),
    (['mueve', 'el', 'esqueleto'], ['bailar-event', 'nothing-event']),
    (['\xc2\xbf', 'bailamos', '?'], ['bailar-event', 'nothing-event']),
    (['bailemos'], ['bailar-event', 'nothing-event']),
    (['vamos', 'a', 'bailar'], ['bailar-event', 'nothing-event']),
    (['\xc2\xa1', 'muevete', '!'], ['bailar-event', 'nothing-event']),
    (['titiru', 'tiru', 'tirutiru'], ['bailar-event', 'nothing-event']),
    (['move', 'your', 'bones', '!'], ['bailar-event', 'nothing-event']),
    (['show', 'me', 'what', 'you', 'got'], ['bailar-event', 'nothing-event']),
    (['bust', 'a', 'move'], ['bailar-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['alza', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['ponte', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'put', 'that', 'object', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'please', 'put', 'the', 'hat', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['grab', 'the', 'hat', 'please'], ['recoger-event', 'nothing-event']),

)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['aarriba', 'dance', 'move', 'ala', 'shake', 'go', 'desplazate', 'quiero', 'ver', 'haciaabajo', 'moverse', 'lo', 'danza', 'baila', ',', 'bust', 'towardsthe', 'to', 'tiru', 'east', 'hat', 'kick', 'cachucha', 'get', 'toupwards', 'de', 'now', 'alza', 'titiru', 'muevas', 'have', 'grab', 'ael', 'el', 'right', 'booty', 'esqueleto', 'gira', 'parala', 'thing', 'tirutiru', 'what', 'dirigite', 'sombrero', 'boogie', 'please', 'todownwards', 'favor', 'ese', 'sur', 'got', '?', 'vamos', 'muevete', 'tus', 'rug', 'bailas', 'bailar', 'cut', 'samba', 'que', 'pontelo', 'put', 'on', '\xc2\xbf', 'sabor', 'vuleve', 'could', 'la', 'turn', 'bailamos', 'south', 'this', 'moneymaker', 'bailemos', 'ahi', 'por', 'azotar', 'down', 'levantalo', 'your', 'levanta', 'esta', 'everybody', 'pares', 'west', 'show', 'podrias', 'head', 'parael', 'north', 'that', 'paraarriba', 'aabajo', 'haciael', 'oeste', 'me', 'te', '\xc2\xa1', 'haciala', 'up', 'paraabajo', 'can', 'moverlo', 'groove', 'este', 've', 'ponte', 'ir', 'it', 'bones', 'want', 'haciaarriba', 'mover', '!', 'thingy', 'objeto', 'no', 'mueve', 'derecha', 'norte', 'baldosa', 'you', 'recogelo', 'may', 'heels', 'I', 'object', 'recoge', 'movimientos', 'a', 'izquierda', 'alzalo', 'tothe', 'the', 'left']), set(['derecha-event', 'mover-event', 'nothing-event', 'bailar-event', 'recoger-event', 'izquierda-event', 'arriba-event', 'abajo-event'])]