"""
Automatically generated Test Data Set
"""

trainingData = (
    (['por', 'favor', 'mover', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['moverse', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'la', 'izquierda', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'abajo', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'parala', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'parael', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['muevete', 'a', 'la', 'derecha', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'a', 'el', 'este', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'hacia', 'el', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['ve', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['ve', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['ve', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['ve', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['ve', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['dirigite', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['dirigite', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['dirigite', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['dirigite', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['gira', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['gira', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['gira', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['gira', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['gira', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['gira', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['vuleve', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['vuleve', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['vuleve', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['ir', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['ir', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['ir', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['ir', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['ir', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['ir', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['desplazate', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['desplazate', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['desplazate', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['desplazate', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['desplazate', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['desplazate', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['desplazate', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['move', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['move', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['move', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'to', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['please', 'move', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['please', 'move', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['please', 'move', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['please', 'move', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'upwards'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['I', 'want', 'you', 'to', 'move', 'to', 'downwards'], ['mover-event', 'abajo-event']),
    (['I', 'want', 'you', 'to', 'move', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['can', 'you', 'please', 'move', 'it', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['go', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['go', 'towards', 'downwards'], ['mover-event', 'abajo-event']),
    (['go', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['turn', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['turn', 'to', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['turn', 'towards', 'the', 'west'], ['mover-event', 'izquierda-event']),
    (['head', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['head', 'towards', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['head', 'towards', 'upwards'], ['mover-event', 'arriba-event']),
    (['head', 'towards', 'the', 'north'], ['mover-event', 'arriba-event']),
    (['head', 'towards', 'the', 'south'], ['mover-event', 'abajo-event']),
    (['could', 'you', 'head', 'to', 'the', 'left'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'to', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'towards', 'the', 'east'], ['mover-event', 'derecha-event']),
    (['could', 'you', 'head', 'towards', 'the', 'right'], ['mover-event', 'izquierda-event']),
    (['\xc2\xa1', 'a', 'bailar', '!'], ['bailar-event', 'nothing-event']),
    (['baila'], ['bailar-event', 'nothing-event']),
    (['\xc2\xbf', 'bailas', '?'], ['bailar-event', 'nothing-event']),
    (['dance', 'now'], ['bailar-event', 'nothing-event']),
    (['everybody', 'dance', 'now'], ['bailar-event', 'nothing-event']),
    (['shake', 'your', 'groove', 'thing'], ['bailar-event', 'nothing-event']),
    (['shake', 'your', 'booty'], ['bailar-event', 'nothing-event']),
    (['cut', 'a', 'rug'], ['bailar-event', 'nothing-event']),
    (['recoge', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['ponte', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'put', 'the', 'hat', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'please', 'put', 'the', 'hat', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['could', 'you', 'please', 'put', 'that', 'thingy', 'on', '?'], ['recoger-event', 'nothing-event']),
    (['please', 'put', 'the', 'hat', 'on'], ['recoger-event', 'nothing-event']),
    (['grab', 'that', 'object'], ['recoger-event', 'nothing-event']),
    (['grab', 'the', 'hat', 'please'], ['recoger-event', 'nothing-event']),

)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['danza', 'dance', 'move', 'hacia', 'go', 'desplazate', 'samba', 'ver', 'la', 'moverse', 'lo', 'show', 'baila', ',', 'bust', 'to', 'arriba', 'tiru', 'east', 'hat', 'kick', 'cachucha', 'get', 'de', 'now', 'alza', 'titiru', 'muevas', 'have', 'grab', 'el', 'right', 'booty', 'shake', 'esqueleto', 'gira', 'parala', 'thing', 'tirutiru', 'what', 'dirigite', 'sombrero', 'boogie', 'please', 'favor', 'ese', 'sur', 'got', '?', 'vamos', 'muevete', 'tus', 'rug', 'bailas', 'bailar', 'cut', 'quiero', 'que', 'pontelo', 'put', 'on', '\xc2\xbf', 'sabor', 'vuleve', 'could', 'turn', 'bailamos', 'south', 'moneymaker', 'bailemos', 'ahi', 'por', 'azotar', 'down', 'levantalo', 'your', 'levanta', 'esta', 'everybody', 'pares', 'west', 'podrias', 'head', 'parael', 'north', 'that', 'paraarriba', 'abajo', 'oeste', 'me', 'te', '\xc2\xa1', 'this', 'up', 'paraabajo', 'can', 'moverlo', 'groove', 'este', 've', 'ponte', 'ir', 'it', 'heels', 'want', 'bones', 'mover', '!', 'thingy', 'objeto', 'no', 'downwards', 'mueve', 'derecha', 'norte', 'baldosa', 'you', 'recogelo', 'towards', 'may', 'I', 'object', 'recoge', 'movimientos', 'upwards', 'a', 'izquierda', 'alzalo', 'the', 'left']), set(['derecha-event', 'mover-event', 'nothing-event', 'bailar-event', 'recoger-event', 'izquierda-event', 'arriba-event', 'abajo-event'])]