"""
Automatically generated Test Data Set
"""

trainingData = (
    (['mover', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['mover', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['mover', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['mover', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'hacia', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['moverse', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'hacia', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['moverse', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'arriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'parala', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['muevete', 'paraabajo', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['ve', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['ve', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ve', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['ve', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['dirigite', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['dirigite', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['dirigite', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['dirigite', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['dirigite', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['dirigite', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['dirigite', 'parala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['gira', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['gira', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['gira', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['gira', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['vuleve', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['vuleve', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ir', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['ir', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['ir', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['ir', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['ir', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'a', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['desplazate', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['desplazate', 'a', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['desplazate', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['desplazate', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['desplazate', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['desplazate', 'parael', 'sur'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'bailamos', '?'], ['bailar-event', 'nothing-event']),
    (['recoge', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['recoge', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['alza', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['levanta', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['ponte', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['ponte', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),

)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['el', 've', 'este', 'bailemos', 'alza', 'gira', 'por', 'recogelo', ',', 'esqueleto', 'levantalo', 'hacia', 'parala', 'mover', 'tirutiru', 'desplazate', 'levanta', 'esta', '!', 'quiero', 'pares', 'objeto', 'la', 'moverse', 'sombrero', 'danza', 'baila', 'mueve', 'derecha', 'favor', 'ese', 'arriba', 'sur', 'tus', 'paraarriba', 'baldosa', 'te', 'no', '?', 'vamos', 'cachucha', 'podrias', 'ahi', 'parael', 'tiru', 'muevete', 'norte', 'de', 'abajo', 'bailar', 'alzalo', 'movimientos', 'samba', 'que', 'bailas', 'recoge', 'ver', 'azotar', 'oeste', 'a', 'moverlo', 'sabor', '\xc2\xa1', 'vuleve', 'bailamos', 'dirigite', 'titiru', 'lo', 'izquierda', 'pontelo', 'paraabajo', 'muevas', 'ponte', '\xc2\xbf', 'ir']), set(['derecha-event', 'mover-event', 'nothing-event', 'bailar-event', 'recoger-event', 'izquierda-event', 'arriba-event', 'abajo-event'])]