"""
Automatically generated Test Data Set
"""

trainingData = (
    (['mover', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['mover', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['mover', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['mover', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['mover', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'aarriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'paraabajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'aarriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'haciael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'haciael', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'parael', 'este'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'ael', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'aarriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'haciala', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'paraarriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'paraabajo', '?'], ['mover-event', 'abajo-event']),
    (['muevete', 'ael', 'oeste', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'haciael', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'parala', 'izquierda', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'paraarriba', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['ve', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['ve', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['ve', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['dirigite', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['dirigite', 'haciael', 'este'], ['mover-event', 'derecha-event']),
    (['dirigite', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['dirigite', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['dirigite', 'haciaabajo'], ['mover-event', 'abajo-event']),
    (['gira', 'aarriba'], ['mover-event', 'arriba-event']),
    (['vuleve', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['vuleve', 'ala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['vuleve', 'haciala', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['vuleve', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ir', 'ala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ir', 'ael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['ir', 'ael', 'sur'], ['mover-event', 'abajo-event']),
    (['ir', 'parala', 'derecha'], ['mover-event', 'derecha-event']),
    (['ir', 'parael', 'oeste'], ['mover-event', 'izquierda-event']),
    (['desplazate', 'ael', 'norte'], ['mover-event', 'arriba-event']),
    (['desplazate', 'haciala', 'derecha'], ['mover-event', 'derecha-event']),
    (['desplazate', 'haciaarriba'], ['mover-event', 'arriba-event']),
    (['desplazate', 'paraarriba'], ['mover-event', 'arriba-event']),
    (['desplazate', 'parael', 'norte'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'bailas', '?'], ['bailar-event', 'nothing-event']),
    (['recoge', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['ponte', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),

)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['este', 've', 'aarriba', 'bailemos', 'alza', 'ir', 'por', 'recogelo', 'ala', 'esqueleto', 'levantalo', 'gira', 'haciaarriba', 'parala', 'mover', 'tirutiru', 'desplazate', 'levanta', 'esta', '!', 'quiero', 'pares', 'objeto', 'haciaabajo', 'moverse', 'sombrero', 'danza', 'baila', 'mueve', 'derecha', 'favor', 'ese', 'sur', 'tus', 'paraarriba', 'baldosa', 'te', 'no', '?', 'vamos', 'cachucha', 'podrias', 'ahi', 'parael', 'tiru', 'muevete', 'norte', 'de', 'aabajo', 'bailar', 'alzalo', 'movimientos', 'haciael', 'samba', 'que', 'bailas', 'recoge', 'ver', 'azotar', ',', 'oeste', 'a', 'moverlo', 'sabor', '\xc2\xa1', 'vuleve', 'haciala', 'la', 'dirigite', 'titiru', 'lo', 'izquierda', 'pontelo', 'paraabajo', 'muevas', 'el', 'ponte', '\xc2\xbf', 'bailamos', 'ael']), set(['derecha-event', 'mover-event', 'nothing-event', 'bailar-event', 'recoger-event', 'izquierda-event', 'arriba-event', 'abajo-event'])]