"""
Automatically generated Training Data Set
"""

trainingData = (
    (['mover', 'hacia', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['mover', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['mover', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['mover', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['mover', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['mover', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['mover', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['mover', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['mover', 'a', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['mover', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['mover', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['mover', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['mover', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['mover', 'a', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['mover', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['mover', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['mover', 'para', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['mover', 'para', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['mover', 'para', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['mover', 'para', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['mover', 'para', 'arriba'], ['mover-event', 'arriba-event']),
    (['mover', 'para', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['mover', 'para', 'abajo'], ['mover-event', 'abajo-event']),
    (['mover', 'para', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'hacia', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'a', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'para', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'para', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['por', 'favor', 'mover', 'para', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'para', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['por', 'favor', 'mover', 'para', 'arriba'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'para', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['por', 'favor', 'mover', 'para', 'abajo'], ['mover-event', 'abajo-event']),
    (['por', 'favor', 'mover', 'para', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'arriba'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'abajo'], ['mover-event', 'abajo-event']),
    (['quiero', 'que', 'te', 'muevas', 'para', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'hacia', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'hacia', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['moverse', 'hacia', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['moverse', 'hacia', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'hacia', 'arriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'hacia', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['moverse', 'hacia', 'abajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'hacia', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'a', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'a', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['moverse', 'a', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['moverse', 'a', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'a', 'arriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'a', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['moverse', 'a', 'abajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'a', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['moverse', 'para', 'la', 'derecha'], ['mover-event', 'derecha-event']),
    (['moverse', 'para', 'el', 'este'], ['mover-event', 'derecha-event']),
    (['moverse', 'para', 'la', 'izquierda'], ['mover-event', 'izquierda-event']),
    (['moverse', 'para', 'el', 'oeste'], ['mover-event', 'izquierda-event']),
    (['moverse', 'para', 'arriba'], ['mover-event', 'arriba-event']),
    (['moverse', 'para', 'el', 'norte'], ['mover-event', 'arriba-event']),
    (['moverse', 'para', 'abajo'], ['mover-event', 'abajo-event']),
    (['moverse', 'para', 'el', 'sur'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'la', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'este', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'la', 'izquierda', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'arriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'abajo', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'hacia', 'el', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'la', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'este', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'la', 'izquierda', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'arriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'abajo', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'a', 'el', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'la', 'derecha', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'el', 'este', '?'], ['mover-event', 'derecha-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'la', 'izquierda', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'el', 'oeste', '?'], ['mover-event', 'izquierda-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'arriba', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'el', 'norte', '?'], ['mover-event', 'arriba-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'abajo', '?'], ['mover-event', 'abajo-event']),
    (['\xc2\xbf', 'podrias', 'moverlo', 'para', 'el', 'sur', '?'], ['mover-event', 'abajo-event']),
    (['muevete', 'hacia', 'la', 'derecha', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'hacia', 'el', 'este', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'hacia', 'la', 'izquierda', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'hacia', 'el', 'oeste', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'hacia', 'arriba', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'hacia', 'el', 'norte', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'hacia', 'abajo', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'hacia', 'el', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'a', 'la', 'derecha', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'a', 'el', 'este', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'a', 'la', 'izquierda', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'a', 'el', 'oeste', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'a', 'arriba', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'a', 'el', 'norte', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'a', 'abajo', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'a', 'el', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'para', 'la', 'derecha', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'para', 'el', 'este', 'por', 'favor'], ['mover-event', 'derecha-event']),
    (['muevete', 'para', 'la', 'izquierda', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'para', 'el', 'oeste', 'por', 'favor'], ['mover-event', 'izquierda-event']),
    (['muevete', 'para', 'arriba', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'para', 'el', 'norte', 'por', 'favor'], ['mover-event', 'arriba-event']),
    (['muevete', 'para', 'abajo', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['muevete', 'para', 'el', 'sur', 'por', 'favor'], ['mover-event', 'abajo-event']),
    (['a', 'mover', 'el', 'esqueleto'], ['bailar-event', 'nothing-event']),
    (['mueve', 'ese', 'esqueleto'], ['bailar-event', 'nothing-event']),
    (['mueve', 'el', 'esqueleto'], ['bailar-event', 'nothing-event']),
    (['\xc2\xa1', 'a', 'bailar', '!'], ['bailar-event', 'nothing-event']),
    (['baila'], ['bailar-event', 'nothing-event']),
    (['\xc2\xbf', 'bailas', '?'], ['bailar-event', 'nothing-event']),
    (['\xc2\xbf', 'bailamos', '?'], ['bailar-event', 'nothing-event']),
    (['bailemos'], ['bailar-event', 'nothing-event']),
    (['por', 'favor', ',', 'baila'], ['bailar-event', 'nothing-event']),
    (['no', 'pares', 'de', 'bailar'], ['bailar-event', 'nothing-event']),
    (['vamos', 'a', 'bailar'], ['bailar-event', 'nothing-event']),
    (['danza'], ['bailar-event', 'nothing-event']),
    (['quiero', 'ver', 'tus', 'movimientos'], ['bailar-event', 'nothing-event']),
    (['sabor'], ['bailar-event', 'nothing-event']),
    (['\xc2\xa1', 'muevete', '!'], ['bailar-event', 'nothing-event']),
    (['titiru', 'tiru', 'tirutiru'], ['bailar-event', 'nothing-event']),
    (['recoge', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['recoge', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['recoge', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['recoge', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recoge', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recoge', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['recoge', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['alza', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['alza', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alza', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alza', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['alza', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['levanta', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['levanta', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levanta', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levanta', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['levanta', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'sombrero'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'sombrero', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'el', 'objeto'], ['recoger-event', 'nothing-event']),
    (['ponte', 'el', 'objeto', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'la', 'cachucha'], ['recoger-event', 'nothing-event']),
    (['ponte', 'la', 'cachucha', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['ponte', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'ponte', 'lo', 'que', 'esta', 'ahi'], ['recoger-event', 'nothing-event']),
    (['ponte', 'lo', 'que', 'esta', 'ahi', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['recogelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'recogelo'], ['recoger-event', 'nothing-event']),
    (['recogelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['alzalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'alzalo'], ['recoger-event', 'nothing-event']),
    (['alzalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['levantalo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'levantalo'], ['recoger-event', 'nothing-event']),
    (['levantalo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),
    (['pontelo'], ['recoger-event', 'nothing-event']),
    (['por', 'favor', 'pontelo'], ['recoger-event', 'nothing-event']),
    (['pontelo', 'por', 'favor'], ['recoger-event', 'nothing-event']),

)
inputIdx = {'actionInput': 1, 'wordInput': 0}
categories = [set(['este', 'esta', 'el', 'bailemos', 'alza', 'ahi', 'por', ',', 'esqueleto', 'levantalo', 'hacia', 'mover', 'levanta', '!', 'quiero', 'pares', 'muevete', 'la', 'moverse', 'sombrero', 'danza', 'baila', 'mueve', 'derecha', 'favor', 'ese', 'arriba', 'sur', 'tiru', 'tirutiru', 'te', '?', 'vamos', 'cachucha', 'podrias', 'recogelo', 'tus', 'alzalo', 'para', 'norte', 'de', 'abajo', 'bailar', 'movimientos', 'que', 'bailas', 'pontelo', 'ver', 'recoge', 'oeste', 'a', 'moverlo', 'sabor', '\xc2\xa1', 'objeto', 'no', 'titiru', 'lo', 'izquierda', 'muevas', 'ponte', '\xc2\xbf', 'bailamos']), set(['derecha-event', 'mover-event', 'nothing-event', 'bailar-event', 'recoger-event', 'izquierda-event', 'arriba-event', 'abajo-event'])]