#!python2
#-*- coding: utf-8 -*-
#  TrainingData.py
#  Autor: Larvasapiens <sebasnr95@gmail.com>
#  Fecha creación: 2015-11-02
#  Fecha última modificación: 2015-11-02
#  Versión: 1.0 [Stable]

"""
The training data is a list of tuples, where the first element of the tuple is
a sentence and the second one is its corresponding event in the virtual world.
"""

trainingData = (
    (('mover', 'hacia', 'la', 'derecha'),                            ('action-mover', 'action-derecha')),
    (('mover', 'a', 'la', 'derecha'),                                ('action-mover', 'action-derecha')),
    (('mover', 'para', 'la', 'derecha'),                             ('action-mover', 'action-derecha')),
    (('por', 'favor', 'mover', 'hacia', 'la', 'derecha'),            ('action-mover', 'action-derecha')),
    (('por', 'favor', 'mover', 'a', 'la', 'derecha'),                ('action-mover', 'action-derecha')),
    (('por', 'favor', 'mover', 'para', 'la', 'derecha'),             ('action-mover', 'action-derecha')),
    (('quiero', 'que', 'te', 'muevas', 'hacia', 'la', 'derecha'),    ('action-mover', 'action-derecha')),
    (('quiero', 'que', 'te', 'muevas', 'a', 'la', 'derecha'),        ('action-mover', 'action-derecha')),
    (('quiero', 'que', 'te', 'muevas', 'para ', 'la', 'derecha'),    ('action-mover', 'action-derecha')),
    (('moverse', 'hacia', 'la', 'derecha'),                          ('action-mover', 'action-derecha')),
    (('moverse', 'a', 'la', 'derecha'),                              ('action-mover', 'action-derecha')),
    (('moverse', 'para', 'la', 'derecha'),                           ('action-mover', 'action-derecha')),
    (('¿', 'podrias', 'moverlo', 'hacia', 'la', 'derecha', '?'),     ('action-mover', 'action-derecha')),
    (('¿', 'podrias', 'moverlo', 'a', 'la', 'derecha', '?'),         ('action-mover', 'action-derecha')),
    (('¿', 'podrias', 'moverlo', 'para', 'la', 'derecha', '?'),      ('action-mover', 'action-derecha')),
    (('muevete', 'hacia', 'la', 'derecha', 'por', 'favor'),          ('action-mover', 'action-derecha')),
    (('muevete', 'a', 'la', 'derecha', 'por', 'favor'),              ('action-mover', 'action-derecha')),
    (('muevete', 'para', 'la', 'derecha', 'por', 'favor'),           ('action-mover', 'action-derecha')),
    (('mover', 'hacia', 'el', 'este'),                               ('action-mover', 'action-derecha')),
    (('mover', 'al', 'este'),                                        ('action-mover', 'action-derecha')),
    (('mover', 'para', 'el', 'este'),                                ('action-mover', 'action-derecha')),
    (('por', 'favor', 'mover', 'hacia', 'el', 'este'),               ('action-mover', 'action-derecha')),
    (('por', 'favor', 'mover', 'para', 'el', 'este'),                ('action-mover', 'action-derecha')),
    (('por', 'favor', 'mover', 'al', 'este'),                        ('action-mover', 'action-derecha')),
    (('quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'este'),       ('action-mover', 'action-derecha')),
    (('quiero', 'que', 'te', 'muevas', 'al', 'este'),                ('action-mover', 'action-derecha')),
    (('quiero', 'que', 'te', 'muevas', 'para', 'el', 'este'),        ('action-mover', 'action-derecha')),
    (('moverse', 'hacia', 'el', 'este'),                             ('action-mover', 'action-derecha')),
    (('moverse', 'al', 'este'),                                      ('action-mover', 'action-derecha')),
    (('moverse', 'para', 'el', 'este'),                              ('action-mover', 'action-derecha')),
    (('¿', 'podrias', 'moverlo', 'hacia', 'el', 'este', '?'),        ('action-mover', 'action-derecha')),
    (('¿', 'podrias', 'moverlo', 'para', 'el', 'este', '?'),         ('action-mover', 'action-derecha')),
    (('¿', 'podrias', 'moverlo', 'al', 'este', '?'),                 ('action-mover', 'action-derecha')),
    (('muevete', 'hacia', 'el', 'este', 'por', 'favor'),             ('action-mover', 'action-derecha')),
    (('muevete', 'al', 'este', 'por', 'favor'),                      ('action-mover', 'action-derecha')),
    (('muevete', 'para', 'el', 'este', 'por', 'favor'),              ('action-mover', 'action-derecha')),
    ###
    (('mover', 'hacia', 'la', 'izquierda'),                          ('action-mover', 'action-izquierda')),
    (('mover', 'a', 'la', 'izquierda'),                              ('action-mover', 'action-izquierda')),
    (('mover', 'para', 'la', 'izquierda'),                           ('action-mover', 'action-izquierda')),
    (('por', 'favor', 'mover', 'hacia', 'la', 'izquierda'),          ('action-mover', 'action-izquierda')),
    (('por', 'favor', 'mover', 'a', 'la', 'izquierda'),              ('action-mover', 'action-izquierda')),
    (('por', 'favor', 'mover', 'para', 'la', 'izquierda'),           ('action-mover', 'action-izquierda')),
    (('quiero', 'que', 'te', 'muevas', 'hacia', 'la', 'izquierda'),  ('action-mover', 'action-izquierda')),
    (('quiero', 'que', 'te', 'muevas', 'a', 'la', 'izquierda'),      ('action-mover', 'action-izquierda')),
    (('quiero', 'que', 'te', 'muevas', 'para ', 'la', 'izquierda'),  ('action-mover', 'action-izquierda')),
    (('moverse', 'hacia', 'la', 'izquierda'),                        ('action-mover', 'action-izquierda')),
    (('moverse', 'a', 'la', 'izquierda'),                            ('action-mover', 'action-izquierda')),
    (('moverse', 'para', 'la', 'izquierda'),                         ('action-mover', 'action-izquierda')),
    (('¿', 'podrias', 'moverlo', 'hacia', 'la', 'izquierda', '?'),   ('action-mover', 'action-izquierda')),
    (('¿', 'podrias', 'moverlo', 'a', 'la', 'izquierda', '?'),       ('action-mover', 'action-izquierda')),
    (('¿', 'podrias', 'moverlo', 'para', 'la', 'izquierda', '?'),    ('action-mover', 'action-izquierda')),
    (('muevete', 'hacia', 'la', 'izquierda', 'por', 'favor'),        ('action-mover', 'action-izquierda')),
    (('muevete', 'a', 'la', 'izquierda', 'por', 'favor'),            ('action-mover', 'action-izquierda')),
    (('muevete', 'para', 'la', 'izquierda', 'por', 'favor'),         ('action-mover', 'action-izquierda')),
    (('mover', 'hacia', 'el', 'oeste'),                              ('action-mover', 'action-izquierda')),
    (('mover', 'al', 'oeste'),                                       ('action-mover', 'action-izquierda')),
    (('mover', 'para', 'el', 'oeste'),                               ('action-mover', 'action-izquierda')),
    (('por', 'favor', 'mover', 'hacia', 'el', 'oeste'),              ('action-mover', 'action-izquierda')),
    (('por', 'favor', 'mover', 'para', 'el', 'oeste'),               ('action-mover', 'action-izquierda')),
    (('por', 'favor', 'mover', 'al', 'oeste'),                       ('action-mover', 'action-izquierda')),
    (('quiero', 'que', 'te', 'muevas', 'hacia', 'el', 'oeste'),      ('action-mover', 'action-izquierda')),
    (('quiero', 'que', 'te', 'muevas', 'al', 'oeste'),               ('action-mover', 'action-izquierda')),
    (('quiero', 'que', 'te', 'muevas', 'para', 'el', 'oeste'),       ('action-mover', 'action-izquierda')),
    (('moverse', 'hacia', 'el', 'oeste'),                            ('action-mover', 'action-izquierda')),
    (('moverse', 'al', 'oeste'),                                     ('action-mover', 'action-izquierda')),
    (('moverse', 'para', 'el', 'oeste'),                             ('action-mover', 'action-izquierda')),
    (('¿', 'podrias', 'moverlo', 'hacia', 'el', 'oeste', '?'),       ('action-mover', 'action-izquierda')),
    (('¿', 'podrias', 'moverlo', 'para', 'el', 'oeste', '?'),        ('action-mover', 'action-izquierda')),
    (('¿', 'podrias', 'moverlo', 'al', 'oeste', '?'),                ('action-mover', 'action-izquierda')),
    (('muevete', 'hacia', 'el', 'oeste', 'por', 'favor'),            ('action-mover', 'action-izquierda')),
    (('muevete', 'al', 'oeste', 'por', 'favor'),                     ('action-mover', 'action-izquierda')),
    (('muevete', 'para', 'el', 'oeste', 'por', 'favor'),             ('action-mover', 'action-izquierda')),
    ###
    (('mover', 'hacia', 'arriba'),                                   ('action-mover', 'action-arriba')),
    (('mover', 'a', 'arriba'),                                       ('action-mover', 'action-arriba')),
    (('mover', 'para', 'arriba'),                                    ('action-mover', 'action-arriba')),
    (('por', 'favor', 'mover', 'arriba'),                            ('action-mover', 'action-arriba')),
    (('quiero', 'mover', 'hacia', 'arriba'),                         ('action-mover', 'action-arriba')),
    (('moverse', 'para', 'arriba'),                                  ('action-mover', 'action-arriba')),
    (('¿', 'podrias', 'moverlo', 'hacia', 'arriba', '?'),            ('action-mover', 'action-arriba')),
    ###
    (('mover', 'hacia', 'abajo'),                                    ('action-mover', 'action-abajo')),
    (('mover', 'a', 'abajo'),                                        ('action-mover', 'action-abajo')),
    (('mover', 'para', 'abajo'),                                     ('action-mover', 'action-abajo')),
    (('por', 'favor', 'mover', 'abajo'),                             ('action-mover', 'action-abajo')),
    (('quiero', 'mover', 'hacia', 'abajo'),                          ('action-mover', 'action-abajo')),
    (('moverse', 'para', 'abajo'),                                   ('action-mover', 'action-abajo')),
    (('¿', 'podrias', 'moverlo', 'hacia', 'abajo', '?'),             ('action-mover', 'action-abajo')),
    ###
    (('hacia', 'la', 'derecha'),                                     ('action-nothing', 'action-derecha')),
    (('a', 'la', 'derecha'),                                         ('action-nothing', 'action-derecha')),
    (('para', 'la', 'derecha'),                                      ('action-nothing', 'action-derecha')),
    (('por', 'favor', 'a', 'la', 'derecha'),                         ('action-nothing', 'action-derecha')),
    (('quiero', 'hacia', 'la', 'derecha'),                           ('action-nothing', 'action-derecha')),
    (('para', 'la', 'derecha'),                                      ('action-nothing', 'action-derecha')),
    (('¿', 'podrias', 'hacia', 'la', 'derecha', '?'),                ('action-nothing', 'action-derecha')),
    ###
    (('mover', 'hacia'),                                             ('action-mover', 'action-nothing')),
    (('mover', 'a'),                                                 ('action-mover', 'action-nothing')),
    (('mover', 'para'),                                              ('action-mover', 'action-nothing')),
    (('por', 'favor', 'mover'),                                      ('action-mover', 'action-nothing')),
    (('quiero', 'mover', 'hacia'),                                   ('action-mover', 'action-nothing')),
    (('moverse', 'para'),                                            ('action-mover', 'action-nothing')),
    (('¿', 'podrias', 'moverlo', 'hacia', '?'),                      ('action-mover', 'action-nothing'))
)
    
#actionsData = (
    #('action-mover', 'action-derecha'),
    #('action-mover', 'action-derecha'),
    #('action-mover', 'action-derecha'),
    #('action-mover', 'action-derecha'),
    #('action-mover', 'action-derecha'),
    #('action-mover', 'action-derecha'),
    #('action-mover', 'action-derecha'),
    ####
    #('action-mover', 'action-izquierda'),
    #('action-mover', 'action-izquierda'),
    #('action-mover', 'action-izquierda'),
    #('action-mover', 'action-izquierda'),
    #('action-mover', 'action-izquierda'),
    #('action-mover', 'action-izquierda'),
    #('action-mover', 'action-izquierda'),
    ####
    #('action-mover', 'action-arriba'),
    #('action-mover', 'action-arriba'),
    #('action-mover', 'action-arriba'),
    #('action-mover', 'action-arriba'),
    #('action-mover', 'action-arriba'),
    #('action-mover', 'action-arriba'),
    #('action-mover', 'action-arriba'),
    ####
    #('action-mover', 'action-abajo'),
    #('action-mover', 'action-abajo'),
    #('action-mover', 'action-abajo'),
    #('action-mover', 'action-abajo'),
    #('action-mover', 'action-abajo'),
    #('action-mover', 'action-abajo'),
    #('action-mover', 'action-abajo'),
    ####
    
    #('action-derecha', 'action-nothing'),
    #('action-derecha', 'action-nothing'),
    #('action-derecha', 'action-nothing'),
    #('action-derecha', 'action-nothing'),
    #('action-derecha', 'action-nothing'),
    #('action-derecha', 'action-nothing'),
#)

